name: LoginPrivacy
version: ${project.version}
main: lg.sec.loginprivacy.LoginPrivacy
authors: [ Devie ]
softdepend: [  Multiverse-Core ]
description: Simple authentication plugin!
commands:
  login:
    usage: /login [password]
    description: Login to your server account
    permission: lg.sec.loginprivacy.login
  register:
    usage: /register [password] [password]
    description: Register to your server account
    permission: lg.sec.loginprivacy.register
  setLoginLocation:
    usage: /setLoginLocation
    description: Set specific location to login then teleport to last location
    permission: lg.sec.loginprivacy.setLoginLocation
