# <==================[Login Privacy]==================>
#
#       LLLLLLLLLLL                  PPPPPPPPPPPPPPPPP
#       L:::::::::L                  P::::::::::::::::P
#       L:::::::::L                  P::::::PPPPPP:::::P
#        LL:::::::LL                  PP:::::P     P:::::P
#        L:::::L                      P::::P     P:::::P
#        L:::::L                      P::::P     P:::::P
#        L:::::L                      P::::PPPPPP:::::P
#        L:::::L                      P:::::::::::::PP
#        L:::::L                      P::::PPPPPPPPP
#        L:::::L                      P::::P
#        L:::::L                      P::::P
#        L:::::L         LLLLLL       P::::P
#        LL:::::::LLLLLLLLL:::::L     PP::::::PP
#       L::::::::::::::::::::::L     P::::::::P
#       L::::::::::::::::::::::L     P::::::::P
#       LLLLLLLLLLLLLLLLLLLLLLLL     PPPPPPPPPP
#
# <==================[Login Privacy]==================>
Configuration:
  # There you can disable your server authentication by setting this to 'true'.
  disable-auth: false
  # There you can specify the login message delay in ticks.
  join-message-delay: 100
  # There you can specify.
  join-location:
    # There you can specify where players will be teleported when they connect to the server:
    # 'true' - teleport player to set location for example: 'spawn, hub'
    #  and teleports to the last seen location => if not defined teleport to last location.
    # 'false' - spawns player to the last seen location as normal.
    after-login-teleport-to-last-location: true