# <==================[Login Privacy]==================>
#                88          88888888ba
#                88          88      "8b
#                88          88      ,8P
#                88          88aaaaaa8P'
#                88          88""""""'
#                88          88
#                88          88
#                88888888888 88
# <==================[Login Privacy]==================>
Configuration:
  # There you can disable your server authentication by setting this to 'true'
  disable-auth: false
  # There you can specify the login message delay in ticks
  join-message-delay: 50